# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x05myapp\"\x1c\n\x0b\x44\x61taRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1e\n\x0c\x44\x61taResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2B\n\x0cMyApiService\x12\x32\n\x07GetData\x12\x12.myapp.DataRequest\x1a\x13.myapp.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=20
  _globals['_DATAREQUEST']._serialized_end=48
  _globals['_DATARESPONSE']._serialized_start=50
  _globals['_DATARESPONSE']._serialized_end=80
  _globals['_MYAPISERVICE']._serialized_start=82
  _globals['_MYAPISERVICE']._serialized_end=148
# @@protoc_insertion_point(module_scope)
