# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0evideoprocessor\":\n\x12VideoUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\nvideo_data\x18\x02 \x01(\x0c\"I\n\x13VideoUploadResponse\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"C\n\x0cQueryRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x12\n\nquery_type\x18\x03 \x01(\t\"G\n\rQueryResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"!\n\rStatusRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"N\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1b\n\x13progress_percentage\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2\x92\x02\n\x15VideoProcessorService\x12V\n\x0bUploadVideo\x12\".videoprocessor.VideoUploadRequest\x1a#.videoprocessor.VideoUploadResponse\x12K\n\x0cProcessQuery\x12\x1c.videoprocessor.QueryRequest\x1a\x1d.videoprocessor.QueryResponse\x12T\n\x13GetProcessingStatus\x12\x1d.videoprocessor.StatusRequest\x1a\x1e.videoprocessor.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOUPLOADREQUEST']._serialized_start=29
  _globals['_VIDEOUPLOADREQUEST']._serialized_end=87
  _globals['_VIDEOUPLOADRESPONSE']._serialized_start=89
  _globals['_VIDEOUPLOADRESPONSE']._serialized_end=162
  _globals['_QUERYREQUEST']._serialized_start=164
  _globals['_QUERYREQUEST']._serialized_end=231
  _globals['_QUERYRESPONSE']._serialized_start=233
  _globals['_QUERYRESPONSE']._serialized_end=304
  _globals['_STATUSREQUEST']._serialized_start=306
  _globals['_STATUSREQUEST']._serialized_end=339
  _globals['_STATUSRESPONSE']._serialized_start=341
  _globals['_STATUSRESPONSE']._serialized_end=419
  _globals['_VIDEOPROCESSORSERVICE']._serialized_start=422
  _globals['_VIDEOPROCESSORSERVICE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
