name: Build Backend (Windows .exe)

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "Current path:"
          pwd
          echo "Files:"
          dir

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: video-analyser-backend
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-extras --dev
          pip install pyinstaller

      - name: Build backend with PyInstaller
        working-directory: video-analyser-backend
        run: |
          pyinstaller ^
            --name video_analyzer_backend ^
            --onedir ^
            --noconsole ^
            --add-data "templates;templates" ^
            --add-data "protos;protos" ^
            --add-data ".env;." ^
            --add-data "ml-models;ml-models" ^
            --hidden-import langchain ^
            --hidden-import tiktoken ^
            --hidden-import whisper ^
            --hidden-import ultralytics ^
            server.py

      - name: Upload built exe
        uses: actions/upload-artifact@v4
        with:
          name: video-analyzer-backend-exe
          path: video-analyser-backend/dist/video_analyzer_backend/
